[project]
name = "llm-distillation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "synthetic-data-kit>=0.0.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "rich>=14.1.0",
    "tqdm>=4.67.1",
]
